// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gkojdhxtljsmhqoxgvtp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imdrb2pkaHh0bGpzbWhxb3hndnRwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM1MTA2MTEsImV4cCI6MjA2OTA4NjYxMX0.lAznKx7mZau8IBLm_H5oVVzBbR4AswWEMVFhG4s14H4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});